### ISSUE TITLE
Connect to running VLC instance?

### ISSUE THREAD

**Issue by marvin-yorke** [tjfontaine/node-vlc#3]
Hi,

I'd like to know if it's possible to connect to a running VLC instance? I'd like to play media using VLC GUI and get media info inside of the Node app. Is there any way to do this?

Regards,
Max

**Comment by tjfontaine** [comment]
This module is intended to be a wrapper around libvlc, which is meant for embedding vlc into your application, not for controlling running standard VLC instances. To do that you have two options, enable the http interface and use the api it offers, or enable the RC interface and use that mechanism. You can find more information about those here http://www.videolan.org/doc/play-howto/en/ch04.html#id590873

I'm closing this ticket for now, I'm not opposed to writing a module for communicating with the RC interface, but it would probably be a separate module entirely.
